[package]
name = "gi"
version = "0.1.7"
edition = "2024"
description = "git interactive cli tool"
license-file = "LICENSE"
repository = "https://github.com/tsumli/gi"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
git2 = "0.20.2"
inquire = "0.9.1"
thiserror = "2.0"
