[package]
name = "gi"
version = "0.1.0"
edition = "2021"
description = "git interactive cli tool"
license-file = "LICENSE"
repository = "https://github.com/tsumli/gi"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
git2 = "0.19.0"
inquire = "0.7.5"
